services:
  - type: web
    name: crowdpulse-backend
    env: node
    plan: free
    buildCommand: npm install && npm run install:all && npm run build:prod
    startCommand: npm run start:prod
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 5000
      - key: CORS_ORIGIN
        value: "*"
      - key: MONGO_URI
        value: "mongodb+srv://mydb:mypassword@cluster0.05teq0z.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
